### ISSUE TITLE
feature request - allow weak password for folder sharing

### ISSUE THREAD

**Issue by Kugeleis** [nextcloud/password_policy#165]
A simple password is better than none.
I have a feature request:
When activating link sharing for a folder I would like to provide a simple password for basic access protection. Instead, I’m tutored by the software “this password is among the 1000 most common”.
Shouldn’t the user decide what is appropriate. A hint is ok but not the exclusion.

Here is the use case:
I want to share some pictures with friends from our last hike. It’s nothing highly confidential. I share the link and send it by mail and tell the friends “The password is the village we started in.”
I guess this is better than no password. But since this word is not allowed I set the folder rather to have no password. Bad ending!

The issue was [discussed in the nextcloud help section.](https://help.nextcloud.com/t/allow-simple-password-for-folder-sharing/115318)

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/password_policy/issues/117
