### ISSUE TITLE
time based outdating passwords

### ISSUE THREAD

**Issue by Django-BOfH** [nextcloud/password_policy#27]
Today I was asked, if it were possible to define max. lifetime of a password. 
Users should change passwords every 30 days. :/  
I said, no I did'nt find an option, but I'll aks about a feature-request. ;)

**Comment by Ascendancer** [comment]
Push. This would be a very nice addition to the featureset of this app. I´m also regularily asked about that feature, and this question also arises occasionally on the nextcloud forums.

**Comment by j-ed** [comment]
#50

**Comment by jotoeri** [comment]
#101 🎉 😉
