### ISSUE TITLE
Compress the password lists

### ISSUE THREAD

**Issue by jvoisin** [nextcloud/password_policy#288]
### Steps to reproduce
1. Check the size of the files on the disk
2. Notice that the `lists` folder weights ~20MiB 

### Expected behaviour
A nice small heavily compressed file containing the passwords, decompressed at runtime when needed. Or even better, a serialized and compressed [cuckoo filter](https://en.wikipedia.org/wiki/Cuckoo_filter).

### Actual behaviour
20MiB of text for 100k words.

### Server configuration

**Operating system**: Alpine

**Web server:** Nginx

**Database:** Sqlite

**PHP version:** 8.0.12

**Nextcloud version:** 22.2.0

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by ritzow** [comment]
I would second this as something to improve, although not an issue that causes any problems. When excluding `*.js.map` files, password_policy is one of the largest nextcloud apps, due to the php lists files. The lists take up more space than the entire Nextcloud Talk app. It does make me wonder if this affects memory usage at all.

```
112M  /app/nextcloud_apps/password_policy
108M  /app/nextcloud_apps/password_policy/lists
82M   /app/nextcloud_apps/spreed
47M   /app/nextcloud_apps/collectives
39M   /app/nextcloud_apps/text
27M   /app/nextcloud_apps/richdocuments
27M   /app/nextcloud_apps/calendar
24M   /app/nextcloud_apps/suspicious_login
22M   /app/nextcloud_apps/polls
22M   /app/nextcloud_apps/forms
20M   /app/nextcloud_apps/theming
20M   /app/nextcloud_apps/deck
19M   /app/nextcloud_apps/contacts
18M   /app/nextcloud_apps/files_pdfviewer
15M   /app/nextcloud_apps/viewer
14M   /app/nextcloud_apps/notifications
14M   /app/nextcloud_apps/news
12M   /app/nextcloud_apps/settings
9.8M  /app/nextcloud_apps/circles
7.7M  /app/nextcloud_apps/music
6.9M  /app/nextcloud_apps/user_oidc
6.5M  /app/nextcloud_apps/app_api
5.0M  /app/nextcloud_apps/dav
4.0M  /app/nextcloud_apps/user_ldap
3.8M  /app/nextcloud_apps/files_sharing
```

**Comment by BenWiederhake** [comment]
I use nextcloud with a few friends. Only I can create accounts, so I disabled the "password\_policy" plugin.

It's a bit weird to see that *THIS* consumes over 10% of all space, and I can't uninstall it. Please, come up with a better way to handle this.

Here's a quick-and-dirty workaround that replaces all "password lists" with empty lists:

```
<?php
return array ();
```
Write this to `apps/password_policy/lists/list-*.php` after every update.
