### ISSUE TITLE
minimum pasword length differs in doc vs. nc

### ISSUE THREAD

**Issue by schaechtelchen** [nextcloud/password_policy#299]
### Steps to reproduce
1. See https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_password_policy.html
2. See https://your-nextcloud/index.php/settings/admin/security
3. Password length 8 vs. 10

### Expected behaviour
The documentation should tell about the minimum password length of 10

### Actual behaviour
Doc says 8

### Server configuration

**Nextcloud version:**
Nextcloud 22.2.3

**Comment by susnux** [comment]
Was fixed on the docs by @kesselb with https://github.com/nextcloud/documentation/pull/10949
