### ISSUE TITLE
missing error msg when creating user with weak passwd

### ISSUE THREAD

**Issue by quenenni** [nextcloud/password_policy#32]
Debian Jessie
Nextcloud 10
Password Policy 1.0.0 & 1.1.0
--------------

When I create a user from the Users page, if the password doesn't respect the rules, the user is not created, but no error msg is showed to indicate why.

I must say that's very confusing. It took us a while to understand where the problem was coming from as the only log found is a 403 response in nginx access log:
x.x.x.x - - [20/Dec/2016:17:02:16 +0100] "POST /index.php/settings/users/users HTTP/2.0" 403 6775 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
.
Anyway.. Thanks for this excellent application.

**Comment by ondrejlinha** [comment]
I have very similar problem with my nc11 installation.

If you try to share file with simple password protection, javascript shows only 'Error' not regular error/warning message.

Steps to reproduce:
* Install Nextcloud11 (Nginx with PHP5-fpm)
* Login to the admin area, select sharing section and check 'Enforce password protection'
* Try to share file with simple password

With Apache2 works everything fine.

**Comment by tomajask** [comment]
I'm using NextCloud 11.0.2.7 version and this problem still occurs.

**Comment by rullzer** [comment]
Are you by any chance using nginx?

If so, disable the error pages. Beacuse that converts the error.

**Comment by rullzer** [comment]
This is caused by

```
error_page 403 /core/templates/403.php;
error_page 404 /core/templates/404.php;
```

In the nginx config. Please move those lines.

**Comment by quenenni** [comment]
It's only the line
```
error_page 403 /core/templates/403.php;
```
that causes the problem.

Where am I suppose to move it? In the .user.ini from the nextcloud folder?
