### ISSUE TITLE
Length filed is not writable in current master

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/password_policy#37]
Nextcloud 11.0:

<img width="271" alt="bildschirmfoto 2017-03-06 um 20 20 51" src="https://cloud.githubusercontent.com/assets/19711361/23625727/714a5374-02aa-11e7-96cd-3dfdee5446d0.png">

latest `master`:

<img width="235" alt="bildschirmfoto 2017-03-06 um 20 19 07" src="https://cloud.githubusercontent.com/assets/19711361/23625703/60b755f2-02aa-11e7-815d-cb3dd8a1aca5.png">

I am not able to see the content of the "length"-field in the latest master ... seems to be caused by the scss and button changes 😞

**Comment by rullzer** [comment]
Fixed in #41
