### ISSUE TITLE
Typo haveibeenpwned/haveibeenpwnd (missing an "e")

### ISSUE THREAD

**Issue by chk1** [nextcloud/password_policy#64]
tomharristech pointed out on [in a Twitter reply](https://twitter.com/Nextclouders/status/983669931467329536) that there's a typo in the HIBP checkbox in admin settings: 

Incorrect: `haveibeenpwnd.com`
Correct: `haveibeenpwned.com` (according to the [HIBP Twitter account](https://twitter.com/haveibeenpwned) and [website](https://haveibeenpwned.com))

The typo is present in all translations:
https://github.com/nextcloud/password_policy/search?utf8=%E2%9C%93&q=haveibeenpwnd&type=

**Comment by MariusBluem** [comment]
Until your PR is not merged, the issue is still existing and should not be closed for that reason. @rakekniven

**Comment by rakekniven** [comment]
Can this issues assigned to a milestone as well?
