### ISSUE TITLE
untranslatable part found in app

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/password_policy#66]
i discovered a part of text in password_policy that can't get translated by transifex. 
(since i somehow can't get my screenshot uploaded here, i am linking to the issue over there in [the nextcloud forum](https://help.nextcloud.com/t/untranslated-parts-in-apps/31555) ...

i guess that issue isn't depending on any of my environment. if though you might need some more info - other than NC 13.0.2.1. and password_policy 1.3.0 - let me know

@rakekniven wanted to get mentioned here... ;)

![fd75f017bea6e19571d9e10c363b64847dbe802f_1_690x134](https://user-images.githubusercontent.com/2069590/40114654-02cd46f2-590e-11e8-9932-6ef1483f010d.png)

**Comment by rullzer** [comment]
Fixed with #67 thnx!
