### ISSUE TITLE
Add API for web/clients

### ISSUE THREAD

**Issue by rullzer** [nextcloud/password_policy#82]
As discussed several times (latest with @skjnldsv) a proper API would make sense.

There are only two very basic methods:

* Validate
* Generate

Probably a simple OCS endpoint would do the trick.
We could expose it in the capabilities we already expose. So the link can easily be used

**Comment by skjnldsv** [comment]
If possible, a js endpoint would be awesome too :)
Maybe exposing a regex? Or something?

**Comment by rullzer** [comment]
There is no way to expose a proper regex like that. Since the sane password rules require checking against the common passwords and HIBP.

**Comment by skjnldsv** [comment]
I forgot about that, let's use the php request then :)
